#
# Makefile for the Linux Bluetooth HCI device drivers.
#

include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y        += -I$(srctree)/arch/arm/mach-$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/dct/dct


obj-$(CONFIG_BRCM_BT)		+= brcm-bluetooth-rfkill.o


